### ISSUE TITLE
Cannot download an existing file

### ISSUE THREAD

**Issue by tomicvladan** [fairDataSociety/fairOS-dfs#125] opened 2021-10-28 13:25 UTC
**Describe the bug**
When trying to download a file which already exists using this endpoint `GET https://fairos.fairdatasociety.org/v1/file/download?file_path=/reactjs.org/filename.json&pod_name=Podname` the response is:

`{"message":"download: file not present","code":500}`

**Comment by tfius** [comment] 2021-11-10 13:39
can't reproduce

**Comment by asabya** [comment] 2022-01-13 06:34
closing this for now

**Closed by asabya** 2022-01-13 06:34 UTC
Labels: bug, can't reproduce
