### ISSUE TITLE
Incorrect message after file upload

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairOS-dfs#76] opened 2021-07-03 11:19 UTC
After file uploading to root fairOS return message
```
{
  Responses: [ { file_name: 'info.json', message: 'directory not present' } ]
}
```
but root directory present and file uploaded successfully

**Comment by asabya** [comment] 2021-12-24 05:33
Unable to reproduce in https://github.com/fairDataSociety/fairOS-dfs/releases/tag/v0.7.2. Closing this for now

**Closed by asabya** 2021-12-24 05:33 UTC
