### ISSUE TITLE
Incorrect behaviour on file delete

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairOS-dfs#77] opened 2021-07-03 11:21 UTC
After deleting a file from root directory of pod, I receive this message
```
{
  Responses: [ { file_name: 'info.json', message: 'error uploading data' } ]
}
```
but file deleted successfully

**Comment by asabya** [comment] 2021-12-22 07:32
Unable to reproduce in latest version

**Comment by asabya** [comment] 2021-12-24 05:32
Closing this for now

**Closed by asabya** 2021-12-24 05:32 UTC
