### ISSUE TITLE
Can't delete a Pod

### ISSUE THREAD

**Issue by tmm360** [fairDataSociety/fairOS-dfs#58] opened 2021-02-15 18:33 UTC
**Describe the bug**
It's not clear how to delete a Pod.

This is a raw request for delete:
```
DELETE http://localhost:9090/v0/pod/delete?name=dbTest HTTP/1.1
Host: localhost:9090
Accept: application/octet-stream
Cookie: fairOS-dfs=MTYxMzQxMzYxNnxIVzUwLW54TW01Wm1qMTJuVDV1SC1jdERmMEhVZ2d2UFVwTlZRNGVrUUlkSVNiYm5YdFpQdDFDY1lQS3dNYU9xWHRTX0FiaFNMTWwyZTBIXzhZNkFYdDZVUUYzZU1ucGEzZkxZUkNwNk00RHl5bE9WdUNYTndQWmpRYTZmMzE5d3ZoS09zaU5jVXRqa2RTV19oSFNpeUZIUEdfT3h0bDByS05scVFnPT1864BgJRaqY0bGEgoroW9jNc7m_AWNsY8Tsu-7aXSqdzE=
```

This is the response:
```
HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=utf-8
Vary: Origin
Date: Mon, 15 Feb 2021 18:27:08 GMT
Content-Length: 74

{"message":"delete pod: \"pod\" parameter missing in cookie","code":400}
```

The response requests for a specific formed cookie, that should be returned with the pod opening, but it isn't.

This is a sample raw request for open a pod:
```
POST http://localhost:9090/v0/pod/open?pod=dbTest&password=pswTest HTTP/1.1
Host: localhost:9090
Accept: application/octet-stream
Cookie: fairOS-dfs=MTYxMzQxMzYxNnxIVzUwLW54TW01Wm1qMTJuVDV1SC1jdERmMEhVZ2d2UFVwTlZRNGVrUUlkSVNiYm5YdFpQdDFDY1lQS3dNYU9xWHRTX0FiaFNMTWwyZTBIXzhZNkFYdDZVUUYzZU1ucGEzZkxZUkNwNk00RHl5bE9WdUNYTndQWmpRYTZmMzE5d3ZoS09zaU5jVXRqa2RTV19oSFNpeUZIUEdfT3h0bDByS05scVFnPT1864BgJRaqY0bGEgoroW9jNc7m_AWNsY8Tsu-7aXSqdzE=
Content-Type: application/octet-stream; charset=utf-8
Content-Length: 0

```

Response:
```
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Vary: Origin
Date: Mon, 15 Feb 2021 18:26:58 GMT
Content-Length: 50

{"message":"pod opened successfully","code":200}
```

No new cookie is returned.

**Expected behavior**
The pod should be deletable without any special cookie in request, apart from the user authentication.

**Comment by asabya** [comment] 2022-01-10 05:23
Unable to reproduce this. Pod delete behaviour has changed to some extent. Please check if you are still facing it. 

Closing it.

**Closed by asabya** 2022-01-10 05:23 UTC
