### ISSUE TITLE
Error when creating a pod which was previously deleted

### ISSUE THREAD

**Issue by tomicvladan** [fairDataSociety/fairOS-dfs#124] opened 2021-10-26 12:23 UTC
**Describe the bug**
When this endpoint `POST https://fairos.fairdatasociety.org/v1/pod/new` is called for a pod which was previously deleted, the response is:

`{"message":"pod new: error uploading data","code":500}`

**Comment by asabya** [comment] 2021-11-03 11:25
This should be gone once #118 is resolved

**Comment by asabya** [comment] 2021-11-03 12:06
duplicate of #117

**Closed** 2021-11-17 13:32 UTC
Labels: bug
