### ISSUE TITLE
Incorrect time fields

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairOS-dfs#85] opened 2021-07-04 08:57 UTC
1) Login
2) Call /dir/ls method inside any pod with files
3) It return info like that:
```
{
  entries: [
    {
      name: 'feed.json',
      content_type: '',
      size: '10',
      block_size: '1000000',
      creation_time: '1625388793',
      modification_time: '1625388793',
      access_time: '1625388793'
    }
  ]
}
```
4) Call /dir/ls again
5) Fields creation_time, modification_time, access_time will be different every time

Expected:
creation_time, modification_time are should be static

**Comment by asabya** [comment] 2021-12-24 05:29
Unable to reproduce in https://github.com/fairDataSociety/fairOS-dfs/releases/tag/v0.7.2

After uploading I get the following
```
{
    "files": [
        {
            "name": "somefile.json",
            "content_type": "text/plain; charset=utf-8",
            "size": "850",
            "block_size": "1000000",
            "creation_time": "1640323508",
            "modification_time": "1640323508",
            "access_time": "1640323508"
        }
    ]
}
```

after few times calling the `ls` api, I get the same timestamp. After Downloading the file once I get the following 
```
{
    "files": [
        {
            "name": "somefile.json",
            "content_type": "text/plain; charset=utf-8",
            "size": "850",
            "block_size": "1000000",
            "creation_time": "1640323508",
            "modification_time": "1640323508",
            "access_time": "1640323570"
        }
    ]
}
```

So I guess it got fixed with some other changes.

**Closed** 2022-01-10 04:30 UTC
